export enum ItemType {

	AIR_CONDITIONER, AIR_MEASURING_DEVICE, INSTRUMENTS, AIRCRAFT_PARTS, ATHLETIC_GOODS, ATV, AUTOMOBILE_ENGINE, AXLES, AUTOMOBILE, BOOKS, BUFFET, HUTCH, CHINA_CABINET, CHAIRS, CHAIRS_UPHOLSTERED, CHARCOAL, CHINAWARE, EARTHENWARE_STONEWARE, CLOTHING, COMPUTER_SYSTEMS, DEVICES, CONTROL_PANELS, CURIO_CABINET, DESK_WOODEN, DOUGH_WORKING_MACHINE, ELECTRIC_APPLIANCES, ELECTRIC_CONTROL_PANEL, SWITCHBOXES, ELECTRIC_FRYERS, ELECTRIC_GENERATOR, GAS_GENERATOR, GRILLS_OUTDOOR, HAND_TOOLS, HEADBOARD, FOOTBOARD_SIDERAILS, HELICOPTER_ROTOR_BLADES, HOUSEHOLD_GOODS, ICE_CREAM_MAKER, ICE_MACHINE, LAWN_MOWER_DECK, LUMBER, MACHINERY_MACHINERY, MARBLE_STONE_SLABS, MATTRESS_BOXSPRING, MEDICAL_INSTRUMENTS_OR_MACHINES, METAL_ARTICLES, MIRROR, MOTORCYCLE_PARTS, MOTORCYCLE_SCOOTERS, NIGHT_STANDS, ARMOIRE, DRESSERS, BUREAUS, OUTBOARD_MOTOR, PANELS_OR_BLOCKS, RUGS, SAFES, SOFA_LOVESEAT_LOUNGES, TABLES_WOODEN, TELEVISONS, TRANSMISSION_AND_PARTS, TRUCK_BED, BODY_SECTIONS, TUNERS, AMPLIFIERS, RADIOS, TURBINES, VENDING_MACHINE, VITAMINS_OR_MEDICINES, WELDERS

}

